version: '3.7'

volumes:
  data:

services:
  authentication_api:
    container_name: auth_db
    image: "postgres:latest"
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin